import type { CityConfig } from '@/types'

export const GLOBAL_CITIES: CityConfig[] = [
  {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
    currency: 'USD',
    population: 8336817,
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    currency: 'GBP',
    population: 8982000,
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    population: 13960000,
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    currency: 'AED',
    population: 3478000,
  },
  {
    id: 'delhi',
    name: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.6139,
    longitude: 77.209,
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    population: 32941309,
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    currency: 'EUR',
    population: 2161000,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: 'Asia/Singapore',
    currency: 'SGD',
    population: 5850342,
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
    currency: 'AUD',
    population: 5312000,
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
    currency: 'CAD',
    population: 2930000,
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 52.52,
    longitude: 13.405,
    timezone: 'Europe/Berlin',
    currency: 'EUR',
    population: 3769000,
  },
]

export const DEFAULT_MAP_CENTER: [number, number] = [20, 0]
export const DEFAULT_MAP_ZOOM = 2
export const CITY_COUNT = GLOBAL_CITIES.length
export const CITY_IDS = GLOBAL_CITIES.map((c) => c.id)
export const CITY_CURRENCIES = [...new Set(GLOBAL_CITIES.map((c) => c.currency))]
